name: video_converter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5

  get_storage: ^2.1.1
  file_picker: ^5.2.9
  flutter_ffmpeg: ^0.4.0
  
  flutter: 
    sdk: flutter
  path_provider: ^2.0.14

  image: ^4.0.15
  share_plus: ^6.3.2
  gallery_saver: ^2.3.2
 
 

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

